version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/vue-front
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: hooks/update_fornt_vue.sh
      timeout: 180
      runas: ubuntu
#
#    - location: scripts/health_check.sh
#      timeout: 200
#      runas: ubuntu
#
#    - location: scripts/switch.sh
#      timeout: 180
#      runas: ubuntu
